### ISSUE TITLE
Add option to easily make and attached photo of reciept etc. to booking

### ISSUE THREAD

**Issue by poVoq** [moneymanagerex/android-money-manager-ex#1112] opened 2017-03-22 18:59 UTC
Some other similar Android apps allow a quick access to the Android camera to snap a photo of the item bought or the reciept etc. to add as an attachment to the booking.

Would be nice to have in MMEx as well (because otherwise it is way better).

**Comment by MisterY** [comment] 2017-03-25 22:06
Duplicate of #11

**Closed by MisterY** 2017-03-25 22:06 UTC
