### ISSUE TITLE
Errors on Entities>Categories when editing a subcategory on 11'' tablet landscape orientation 

### ISSUE THREAD

**Issue by battmanpcb** [moneymanagerex/android-money-manager-ex#1734] opened 2024-07-05 17:32 UTC
**Describe the bug**
Errors appear when I try to  Edit a subcategory using a 11" tablet in landscape orientation. 
**To Reproduce**
Having the tablet orientation as landscape:
1. Go to Entities>Categories in the side menu
2. Select Edit on the long press menu of the first subcategory 

**Expected behavior**
No errors on editing a subcategory 

**Device Information:**
 - Device: Galaxy Tab S7
 - OS:  Android 13
 - Storage: Google Drive 
 - Synchronization:  Enabled with 10 min interval and Sync on Start
 - Encrypted: IDK
 - App Version: 2024.07.04

**Additional context**
With the tablet in portrait orientation it works great. Perhaps there is something wrong with the Fragment manager.

**Comment by guanlisheng** [comment] 2024-07-07 01:15
thanks @battmanpcb , this might be a bug and let us take a look.

**Comment by wolfsolver** [comment] 2024-07-23 13:41
I try with fresh Pixel 11" (virtual device) and I'm not able to reproduce crash (Category and Payee work fine). Maybe some additional info are needed

**Comment by guanlisheng** [comment] 2024-09-01 05:47
hi @battmanpcb , i am going to close this if there is no further issue

**Closed** 2024-09-02 04:29 UTC
Labels: bug
