### ISSUE TITLE
External DB sync doesn't trigger in-app DB refresh

### ISSUE THREAD

**Issue by technodrome** [moneymanagerex/android-money-manager-ex#711] opened 2016-03-03 14:39 UTC
I usually sync the AMMEX DB with owncloud via webdav (through android FolderSync app). However, even when the new DB is downloaded from the cloud to the folder where AMMEX is expecting it, it will not trigger the DB refresh. I always have to kill the app and start it anew. Only then will it show the transactions added on my desktop. 

This is incredibly frustrating. Hope there's a file-change check in store to fix this.

**Comment by MisterY** [comment] 2016-03-03 14:42
Unlike on desktops, this is not easy to implement as the whole data access mechanism relies completely on Android system, but will look more into the matter to see what the options are (if any).

**Comment by technodrome** [comment] 2016-03-03 14:44
Thanks for your expedient reply. I guess to put a check in place to compare old and new MD5 hash of the DB file could be doable. Or is this not the case?

**Comment by MisterY** [comment] 2016-03-03 14:44
My understanding is that the connection is always closed after the data is loaded. Hence, any new data fetch will open a new connection. This will load the data from the (updated) database file. There might be a different cause to this.

**Comment by technodrome** [comment] 2016-03-03 14:45
I'm using cyanogenmod with the newest lollipop. Happy to provide logcat output or any other debug info you need.

**Comment by MisterY** [comment] 2016-03-03 15:04
This is an interesting point. I have just reproduced this. The data is still shown even after replacing the database with the version where the new record does not exist.
This would also explain the case where swapping the databases results in multiple error messages due to the connections still being connected to the previous database file.

**Comment by technodrome** [comment] 2016-03-03 15:06
That would explain why I just got sqlite slap-across-the-face "Database locked / insert failed" (along these lines).

**Comment by MisterY** [comment] 2016-03-03 16:25
Need to revisit this and double-check that the changes in Android are handled in the code:

- [Vogella](http://www.vogella.com/tutorials/AndroidSQLite/article.html)
- [Android](http://developer.android.com/guide/topics/providers/content-provider-creating.html)

**Comment by MisterY** [comment] 2016-03-03 16:40
Some pointers below. The database **gets cached** by the system so this is difficult to implement, as I originally thought. Still, need a bit more research into available options.

- http://stackoverflow.com/questions/27290966/is-there-a-memory-cache-for-sqlite-in-android-and-how-to-release-or-clear-it

**Comment by technodrome** [comment] 2016-03-03 16:46
I see. 
I missed SSH/webdav sync mechanism in the app so I used external sync program. My point here was obviously to keep the database updated across multiple platforms and devices using NAS/Owncloud (which is, by the way, an absolutely Good Thing™). I know bothering developers with "give us custom sync adapter for service XYZ" wouldn't cut it but now I'm not quite sure how to solve this thing. I am positive one of these days I'll forget to force close app and enter something into that cached copy (if even possible) and see that "Database locked" message.

**Comment by MisterY** [comment] 2016-03-03 16:50
You are absolutely right in the approach. This is what I've been suggesting to users as a workaround to the direct support to multiple different providers out there. However, if these are the consequences then I need to look a bit deeper into this. For now, I hope to find a solution that is as simple as explicitely closing a database but I need to dig deeper and see the differences between database OpenHelper, which is older technology, and the new ContentProvider in Android. One recommends to explicitely close the database while the other mandates that it is not done because "the system" will handle that. 
This last part might be the reason why the app needs to be restarted after the database is replaced in the storage.
I will keep looking into this.

**Comment by technodrome** [comment] 2016-03-03 16:57
I too am positive this is a better way to handle various providers than schizophrenically maintaning myriad of adapters for god knows which service provider happens to be popular these days. I'll keep tabs on your progress and wish you luck in finding the easiest of solutions.

**Comment by MisterY** [comment] 2016-03-03 17:01
Thanks! There a reported solution that I would like to try in the following couple of days. That may solve the issue by closing the database connection after an active database operation is complete.
So far I was under impression that this happens automatically, but the database seems to close only once the application process (not a query) is complete, meaning when an app exists or something like that. I'll update this issue when I have a prototype so you can try it out in a real-world scenario and I might publish a Beta to see if there are any issues for others.
So far I only had an issue sometimes, when switching databases in an emulator so that's my only test scenario for the moment.

**Comment by technodrome** [comment] 2016-03-03 17:19
Fantastic. Thanks.

**Comment by MisterY** [comment] 2016-03-20 18:41
As this is due to the way how Android works with database files, it would be difficult to implement effectively. It is safer to keep the app closed during synchronization and open once the database is synchronized.

**Comment by MisterY** [comment] 2016-04-01 14:56
One thing to try is to introduce a setting for the local db file check. It should be enough to notify a user when the file changes are identified and restart the app.

**Comment by MisterY** [comment] 2018-09-08 06:43
Adding options for exiting the app or closing the current database might help.

**Comment by MisterY** [comment] 2019-02-10 22:34
I think #1278 should resolve this. No workarounds would be necessary. 
Any storage provider can be used equally.

**Closed by MisterY** 2019-02-10 22:34 UTC
Labels: bug, user feedback
