### ISSUE TITLE
app not starting on XIAOMI devices running MIUI

### ISSUE THREAD

**Issue by mouzzza** [moneymanagerex/android-money-manager-ex#1002] opened 2016-09-11 17:29 UTC
As you can read on [forum](http://forum.moneymanagerex.org/viewtopic.php?f=20&t=6785), there is a problem on starting mmex on miui.

Here a log, if you need more, tell me:
`---- 11.09.2016 12:42:39 nachm. ---- 09-11 12:41:07.099 2363 4267 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.money.manager.ex.beta/com.money.manager.ex.home.MainActivity bnds=[480,784][616,920] (has extras)} from uid 10023 on display 0 09-11 12:41:07.199 2363 3500 I ActivityManager: Start proc 18815:com.money.manager.ex.beta/u0a144 for activity com.money.manager.ex.beta/com.money.manager.ex.home.MainActivity 09-11 12:41:07.489 18815 18815 E AndroidRuntime: Process: com.money.manager.ex.beta, PID: 18815 09-11 12:41:07.499 2363 3602 W ActivityManager: Force finishing activity 1 com.money.manager.ex.beta/com.money.manager.ex.home.MainActivity 09-11 12:41:07.589 2363 2383 I ActivityManager: Process com.money.manager.ex.beta (pid 18815) has died 09-11 12:41:35.029 18622 18919 I themeservice: add pending job /data/data/scd.lcex/cache/com.money.manager.ex.beta.png 09-11 12:41:35.099 18622 18938 I themeservice: saving icon for /data/data/scd.lcex/cache/com.money.manager.ex.beta.png 09-11 12:41:35.119 17827 17849 I themeservice: saving icon remotely(18622) for /data/data/scd.lcex/cache/com.money.manager.ex.beta.png ALLOW: true ---- 11.09.2016 12:42:39 nachm. ----`

**Comment by MisterY** [comment] 2016-09-11 21:07
Thanks for the log. However, this does not tell me much. The exception happens only on MIUI ROM. Someone with access to such a device could debug the app and report what causes it.
I may try something with the next Beta version but, to be honest, I have no idea what to look for.

**Comment by MisterY** [comment] 2016-09-12 12:34
Logcat available in the forum [thread](http://forum.moneymanagerex.org/viewtopic.php?f=20&t=6785&sid=30f667432e86da1a5195f31be4b38936&p=14275#p14275).

**Comment by MisterY** [comment] 2016-09-12 12:43
The cause seems to be in String Utils. Try using Text Utils instead.

https://github.com/moneymanagerex/android-money-manager-ex/blob/d60f6699115f5c7d31ad0494005f1329aee12e05/app/src/main/java/com/money/manager/ex/database/ViewMobileData.java#L90

**Comment by mouzzza** [comment] 2016-09-15 06:08
Also v913 isn't starting.
What can I do to give you the right info?

**Comment by MisterY** [comment] 2016-09-15 09:45
Replaced all references to StringUtils in Beta 914.

**Comment by mouzzza** [comment] 2016-09-15 13:31
Looking forward to the new release.

**Comment by MisterY** [comment] 2016-09-15 21:52
Resolved by removing minification as of build 915.

**Comment by jackcsk** [comment] 2017-05-29 06:10
@MisterY: you don't have to disable minification, just add the following line in proguard-rules:
```
-keepnames class org.apache.commons.lang3.** { *; }
```
side-effect is a minor increase in app size, but so far, no other side effect is observed.

**Comment by MisterY** [comment] 2017-05-29 08:07
Thanks, @jackcsk, I'll try that!

**Comment by MisterY** [comment] 2017-05-29 09:35
Rolled out the new Beta. Please try it out and let me know if it works on Xiaomi devices. Thanks!

**Comment by jackcsk** [comment] 2017-06-01 03:08
Tested and verified on XiaoMi HM1S, running Android 4.4.4 (MIUI 7.2)

**Comment by MisterY** [comment] 2017-06-01 10:10
Great, thanks! Will roll this out with the next release, then.

**Closed by MisterY** 2017-06-01 10:10 UTC
Labels: bug
