### ISSUE TITLE
Scan receipts

### ISSUE THREAD

**Issue by Suncatcher** [moneymanagerex/android-money-manager-ex#1380] opened 2019-11-28 18:58 UTC
Any plans to add scanning receipts functionality?

**Comment by luisdev** [comment] 2023-12-24 19:59
Is this the same as #1409?

**Comment by wolfsolver** [comment] 2023-12-30 15:36
Seem yes

**Comment by wolfsolver** [comment] 2024-01-07 17:12
Duplicate of #1409

**Closed** 2024-01-07 17:13 UTC
