### ISSUE TITLE
App getting crashed on editing Loan Account

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1176] opened 2017-12-11 09:34 UTC
Application is getting crashed on editing loan account and working fine with other account types.

Version Tested : 2017.12.06.969-beta

![image](https://user-images.githubusercontent.com/29807533/33824556-ccc2dd50-de84-11e7-9905-254a6ac9fb39.png)

**Comment by Spoker** [comment] 2017-12-11 11:01
I could reproduce it. Never tried editing an account on mobile before, so wasn't aware this was possible.
I guess some things will have to be set in the edit account screen.

Was this built from the dev branch because I'm not sure all the latest updates have been pushed to the beta yet.

**Comment by velmuruganc** [comment] 2017-12-11 13:02
I think the problem is the loan option is not available under account type drop down in account creation screen.

**Comment by Spoker** [comment] 2017-12-11 13:04
Yes, I think so too. I'll try and take a look at it tomorrow if I have time.

**Comment by Spoker** [comment] 2017-12-15 14:19
Should be in next beta. You may close this issue once you have verified it is solved.

**Closed** 2017-12-15 15:00 UTC

**Comment by MisterY** [comment] 2017-12-15 15:05
Thanks!
