### ISSUE TITLE
Support for Nextcloud/Owncloud?

### ISSUE THREAD

**Issue by poVoq** [moneymanagerex/android-money-manager-ex#1104] opened 2017-01-31 19:25 UTC
Would be great to also have support for an open-source personal cloud build in.

**Comment by MisterY** [comment] 2017-02-10 11:30
Duplicate of #685?

**Comment by MisterY** [comment] 2018-09-14 10:08
It does not seem likely that any new providers will be added. Quite the contrary, sync will probably be removed from the app and left out to more specialized apps out there. #1250

**Closed by MisterY** 2018-09-14 10:08 UTC
Labels: duplicate, sync, wontfix
