### ISSUE TITLE
Transaction with "Split Categories" does not show Right balance in Total.

### ISSUE THREAD

**Issue by manmeetjammu** [moneymanagerex/android-money-manager-ex#1316] opened 2019-02-21 09:54 UTC
Transactions with split categories.

I have noticed that above transactions do not show right total in individual cetegory.
They just show the total transaction value and total includes the total transaction value.
Please resolve it in update.

**Comment by MisterY** [comment] 2019-02-24 09:26
Can you please post some screenshots or further details? I've never noticed this and am sure others would report it sometime in the previous years.

**Comment by funrider1** [comment] 2019-02-24 14:00
I had try to understand and was able to reproduce ... hopefully:-)
An example:
- create a split transaction for payee „Shell“ with 25€ for car/gas (category/sub-category) and 10€ for car/carwash
- search for category „carwash“ using the search function in menu bar
- shown result is 35€ for payee „Shell“ with category „split category“

You have to drill down into the Split transaction and then in category field to see the amount for carwash only. The same if you access the data using entity/category, select car/carwash and choose option „show transactions“.

I‘m not sure, but this looks like it is working as designed and supposed?!

**Comment by MisterY** [comment] 2019-02-24 15:07
Thanks, @funrider1, you are right. This is an unfortunate design decision.
In double-accounting systems, i.e. GnuCash, *all* transactions have splits, which show from which accounts the money comes and to which it goes. Here we only have split records for the transactions that have multiple categories.
Unfortunately, yes, this is a design decision, not a bug. If someone has a better implementation, I'm happy to merge a pull request. Hence closing this issue. 
Please reopen if the analysis above is incorrect.

**Closed by MisterY** 2019-02-24 15:07 UTC
