### ISSUE TITLE
Bug found in android-money-manager-ex version 2019.04.10.1000-beta  The application crashes when I click on the Asset Allocation 

### ISSUE THREAD

**Issue by saraji-ali** [moneymanagerex/android-money-manager-ex#1362] opened 2019-05-09 11:36 UTC
# Project Information

* Repository: https://github.com/moneymanagerex/android-money-manager-ex
* Project Name: android-money-manager-ex

# Expected behavior

When I click on the Asset Allocation option, all the options in it should have been displayed.And as I click on this option, the application should not have been crashing

# Actual behavior

The application crashes when I click on the Asset Allocation. 

# How to reproduce

1-[Download ](https://github.com/moneymanagerex/android-money-manager-ex/releases)the app and open it
2- Click the horizontal three line on the top left
3- click on Asset Allocation 
4- see  the bug 

* Browser/App version:  2019.04.10.1000-beta 
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190509_162742](https://user-images.githubusercontent.com/50115498/57450625-d4b3a980-7213-11e9-8d09-aa0465bd8c59.gif)

# My Github Account
https://github.com/saraji-ali

# Logcat

<pre><code>D/AndroidRuntime(17034): Shutting down VM

E/AndroidRuntime(17034): FATAL EXCEPTION: main

E/AndroidRuntime(17034): Process: com.money.manager.ex, PID: 17034

E/AndroidRuntime(17034): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.assetallocation.overview.AssetAllocationOverviewActivity}: android.view.InflateException: Binary XML file line #37: Error inflating class android.support.design.widget.CollapsingToolbarLayout

E/AndroidRuntime(17034): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

E/AndroidRuntime(17034): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime(17034): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime(17034): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime(17034): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(17034): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(17034): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(17034): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(17034): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(17034): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(17034): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(17034): Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class android.support.design.widget.CollapsingToolbarLayout

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(17034): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)

E/AndroidRuntime(17034): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

E/AndroidRuntime(17034): 	at com.money.manager.ex.common.MmxBaseFragmentActivity.setContentView(MmxBaseFragmentActivity.java:75)

E/AndroidRuntime(17034): 	at com.money.manager.ex.assetallocation.overview.AssetAllocationOverviewActivity.onCreate(AssetAllocationOverviewActivity.java:61)

E/AndroidRuntime(17034): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime(17034): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime(17034): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

E/AndroidRuntime(17034): 	... 10 more

E/AndroidRuntime(17034): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CollapsingToolbarLayout" on path: DexPathList[[zip file "/data/app/com.money.manager.ex-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

E/AndroidRuntime(17034): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/AndroidRuntime(17034): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

E/AndroidRuntime(17034): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.createView(LayoutInflater.java:571)

E/AndroidRuntime(17034): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(17034): 	... 22 more

E/AndroidRuntime(17034): 	Suppressed: java.lang.ClassNotFoundException: android.support.design.widget.CollapsingToolbarLayout

E/AndroidRuntime(17034): 		at java.lang.Class.classForName(Native Method)

E/AndroidRuntime(17034): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

E/AndroidRuntime(17034): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

E/AndroidRuntime(17034): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

E/AndroidRuntime(17034): 		... 25 more

E/AndroidRuntime(17034): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
</code></pre>

**Comment by facebook-786** [comment] 2019-05-22 21:53
sir @MisterY please review my post

**Comment by MisterY** [comment] 2019-05-25 19:30
Thank you for the very detailed report. Unfortunately, I no longer have write permissions to the repository and am focusing on creating tools that work with ledger-cli, as it seems to be more comprehensive solution for my needs.

**Comment by devlearner** [comment] 2019-05-26 13:59
@MisterY  oh that's a pity (you've been contributor for such a long time and have done such a great job)  i would've thought and hope you will continue to be the lead.
Thanks for merging my previous PRs.
(just speaking for myself, any chance this be reconsidered (at least stay as a (not so active) maintainer) ? )

@saraji-li   actually i think one of my prs was exactly on this;  i'll just say you may try removing the existing app, and reinstall the latest beta (make sure you pick the link to the right version on the downloads page)

**Comment by MisterY** [comment] 2019-05-26 15:25
Hi, @devlearner, thanks for the kind words. I just cloned the repo again to try to add the new version info and a tag for publishing on FDroid but I'm getting 403. Not sure what has changed there.
Nevertheless, since I am not really using the app any longer, there is not much point in putting valuable time on it. You can see at https://cashier.alensiljak.ml/ something I've done in the past two weeks. 
This little app replaces MMEx on the phone for me. It creates transactions that can be merged to a ledger book. All the functionality of ledger is available on Android through Termux terminal.
There is no need for messing around the build processes, the application is in production within 30 seconds of the last code check-in. It can be used on desktop and pretty much any mobile OS.  On mobile devices, it can be used offline, too.
So, without providing any advice, I can only say that I have found ledger to cover my needs more than any software package I've used so far. And with PWA, I have jumped out of the constant need to upgrade code and libraries simple because of 3rd parties.

**Comment by islam2hamy** [comment] 2021-06-29 06:11
My logcat :

FATAL EXCEPTION: main
Process: com.money.manager.ex, PID: 27250
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.assetallocation.overview.AssetAllocationOverviewActivity}: android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class android.support.v7.widget.LinearLayoutCompat
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class android.support.v7.widget.LinearLayoutCompat
Caused by: android.view.InflateException: Binary XML file line #57: Error inflating class android.support.v7.widget.LinearLayoutCompat
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.LinearLayoutCompat" on path: DexPathList[[zip file "/data/app/com.money.manager.ex-1/base.apk"],nativeLibraryDirectories=[/data/app/com.money.manager.ex-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.money.manager.ex.common.MmxBaseFragmentActivity.setContentView(MmxBaseFragmentActivity.java:75)
	at com.money.manager.ex.assetallocation.overview.AssetAllocationOverviewActivity.onCreate(AssetAllocationOverviewActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by islam2hamy** [comment] 2021-06-29 06:12
Miui : 11.0.2
Android : 7.1.2

**Comment by wolfsolver** [comment] 2024-01-05 20:15
Need to be closed, since asset management was removed.

**Closed** 2024-01-06 13:58 UTC
