### ISSUE TITLE
Filtering entities in Cyrillic is case-sensitive

### ISSUE THREAD

**Issue by Tloo-ZaRaZa** [moneymanagerex/android-money-manager-ex#789] opened 2016-04-11 08:24 UTC
When filtering entities (like accounts or payees) named in Cyrillic, input is case-sensitive.
With input 'счёт' account 'Счёт' is not displayed.

**Comment by MisterY** [comment] 2016-04-11 09:16
Duplicate of #348

**Closed by MisterY** 2016-04-11 09:16 UTC
Labels: duplicate
