### ISSUE TITLE
Auto add scheduled transactions at launch

### ISSUE THREAD

**Issue by AceDenghar** [moneymanagerex/android-money-manager-ex#1683] opened 2024-04-30 07:24 UTC
It would be nice if scheduled transaction could be added automatically when launching the app. It should check what have to be done the current day and apply.

Maybe a checkbox for this 'auto mode' could be added to keep the way it's actually running.

Thanks !

(Sorry for my English)

**Comment by guanlisheng** [comment] 2024-04-30 10:23
Thanks @AceDenghar

May I know your current app info and some typical usage if possible?

**Comment by AceDenghar** [comment] 2024-04-30 10:52
I'm using v2024.04.21 version.

I have some scheduled transactions :

![Screenshot_20240430-123719-01.jpeg](https://github.com/moneymanagerex/android-money-manager-ex/assets/69914581/235915a5-9e51-4d2b-ad5d-d5ddf8972155)

When the scheduled day arrive, I just have a notification to remind me to create the next occurrence for this scheduled transaction :

![Screenshot_20240430-124608-01.jpeg](https://github.com/moneymanagerex/android-money-manager-ex/assets/69914581/1e8f1072-1327-4e8f-9af9-4c40cec07613)

And it sets the new instance for the current day and schedule the next one to the date and then I'll have a new notification , etc...

So, because in scheduled transaction we set the start date and when it occurs, and until when, why is it not automatically applied ?

I understand it's useful if you have to make a physical paiement action, I mean in real life, but maybe in scheduled transaction's options we could set if it  should be automatically applied to be related to automatics bills, etc...

I'm very sorry for my English, hopping it's all clear.

**Comment by smjohns** [comment] 2024-05-01 21:31
I would also like this feature to be considered and have raised it myself in the past. I have 17+ transactions that apply each month and having to step through them is a bit labourious.

Anything you can do to automate this process would be amazing

**Comment by guanlisheng** [comment] 2024-05-07 05:27
hi @AceDenghar, and @smjohns 

here is some progress that MMEX would add scheduled transition along with the notifications.

can you have a try and feedback is welcomed:

https://drive.google.com/file/d/1j2kMPI2VEiFPAheeEsN1XgIB2fNn6Zrs/view?usp=sharing

**Comment by smjohns** [comment] 2024-05-07 11:53
Thanks. Have installed the new version and enabled logging. This has now allowed me to enable notifications but there are no categories to select. Will see how testing goes.

**Comment by guanlisheng** [comment] 2024-05-07 12:16
Just setup some scheduled transactions with proper due date, then re-start the app.

**Comment by smjohns** [comment] 2024-05-07 14:21
Hi,

So I have set up a scheduled transaction for today and tomorrow and shut down the app. When I relaunched it, today’s transaction got inserted automatically so from my perspective that works a treat. I also got a notification about there being expired schedule transactions but this didn’t really apply as the expired transaction was automatically processed. A couple of enhancements to this new capability:

1) It would be useful to have a settings option to switch the auto processing of scheduled transactions on/off as some might just want a notification but not automatically apply the transaction.
2) If the user has auto processing switched off, it would be a nice enhancement if the app displays a reminder pop-up each time the app is launched, confirming “There are ‘nn’ scheduled transactions awaiting processing. Do you want these automatically applied? Y/N”. This would sort of do away with the need for a notification about expired scheduled transactions?
3) The notification issued is “There are expired scheduled transactions”. This works if the transactions are not being automatically applied but in my example, they were automatically applied so the notification was incorrect. In such scenarios maybe a notification confirming that “Scheduled transactions have been automatically applied” if you have this feature switched on.

I will continue playing but nice work on this.

**Comment by AceDenghar** [comment] 2024-05-07 15:14
Hi,

I just installed this version.

I have a scheduled transaction set for tomorrow so I'll have a look.

As mentioned before, an option to set by scheduled transaction if it has to be automatically applied would be nice to permit someone to realize a paiement action (sorry for my English). 

Will tell you tomorrow 👍

**Comment by AceDenghar** [comment] 2024-05-08 06:32
Hi,

It's working well ! Thanks !

Waiting for the 'auto commit' option and it will be perfect ! 

Great job 👍

**Comment by smjohns** [comment] 2024-05-08 06:48
I echo the above comments. The notification fix / auto scheduled transaction processing seems to be working as planned. Hopefully you can implement a couple of the suggestions above to make this feature perfect :)

**Comment by luisdev** [comment] 2024-05-09 16:39
I haven't tested this yet, but is there a way to turn it OFF? I personally don't want _any_ transactions to be automatically entered. I prefer to review and manually "accept" all my scheduled transactions.

Is there an app Setting that allows you turn this "auto add scheduled transactions" feature on or off?

**Comment by AceDenghar** [comment] 2024-05-09 16:47
@luisdev , we asked for these options.

It would be nice if we could set, by scheduled transaction, if it has to be automatically applied or not.

So you could use it your way, as I could use it my way 😉

We're waiting for this and it would be perfect for everyone 🤗

**Comment by guanlisheng** [comment] 2024-05-09 23:10
forgot to update here:  to keep the application simple, scheduled notifications and exec share the same setting.  we may need to polish the message in the future as you suggested.

**Comment by smjohns** [comment] 2024-06-01 09:16
Quick update on this new feature. I'm running v2024.05.09 (1032) and had some scheduled transactions due today (01/06/24). The app was open in the background and when I checked my phone today there was a notification about due scheduled transactions but with I launched the app they did not apply automatically. 

I forced closed the app and relaunched it and the transactions then applied correctly. Not sure if this is a bug or expected behaviour?

**Comment by guanlisheng** [comment] 2024-06-03 05:06
thanks @smjohns, 
this is an expected behaviour that i think can be improved in the near future.

**Comment by jorgeEF** [comment] 2024-06-10 04:25
Hi.. this request has broken my years of usage of mmex: Today I've found that recurring transactions now apply automatically avoiding any manual control that I really must do before the transaction geta confirmed: for me recurring transactions aren't due to an specific day but events that should happen in the month and serve me as a reminder..  this month I didn't get paid or payed stuff that mmex now registered and confirmed. Please, revert this change and add an option to process automatically recurring transactions if the user prefers to... Sorry if I sound entitled but this change really screwed my financial registry and it will take days to fix..

**Comment by luisdev** [comment] 2024-06-10 06:00
I have to agree. There needs to be an option in the MMEX settings to turn the automatic entering of scheduled transactions on or off.

**Comment by guanlisheng** [comment] 2024-06-10 07:34
hey @jorgeEF and @luisdev, please use the previous version as a quick fix if this change is annoying. 

This is still in WIP and might require more time to design and reach the ideal status.

**Comment by guanlisheng** [comment] 2024-06-25 02:49
please try https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.06.25.1034 and going to close this issue.

**Closed by guanlisheng** 2024-06-25 02:49 UTC
Labels: feature

**Comment by jorgeEF** [comment] 2024-06-25 02:53
> please try https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.06.25.1034 and going to close this issue.

Thanks.. this will prevent scheduled transactions to automatically complete at due date?

**Comment by jorgeEF** [comment] 2024-07-11 02:54
Hello again.. can you please set "execution scheduled transaction overdue" disabled by default? It's the behavior the app always had.. I'm asking for it because today I had more than 10 overdue transactions that I must manually complete because sometimes the date passes as it is not a written in stone date.. what happened is that I updated the app and as the date was overdue it confirmed all these transaction because default setting is enabled to automatically process the transaction at overdue.. I don't want it to happen again in a future update please, it takes hours to fix my db again when transactions ocurrs automatically.

**Comment by guanlisheng** [comment] 2024-07-15 13:28
https://github.com/moneymanagerex/android-money-manager-ex/pull/1737 will set default value as false.

**Comment by islam2hamy** [comment] 2024-09-03 09:48
@guanlisheng 
Auto add scheduled transactions does not work in last 2 released "2024.08.25"

**Comment by wolfsolver** [comment] 2024-09-03 10:47
Did you have enable settings?

![Screenshot_20240903-124346-475.png](https://github.com/user-attachments/assets/b40966d7-cba5-4f3a-b01f-ca47fbbc9bb2)

**Comment by islam2hamy** [comment] 2024-09-03 12:02
Yes

![IMG_٢٠٢٤٠٩٠٣_١٥٠١٥٩](https://github.com/user-attachments/assets/0495a55e-e840-45ad-addd-6d4cdb937719)

![IMG_٢٠٢٤٠٩٠٣_١٥٠١٤٢](https://github.com/user-attachments/assets/fb4ea108-bec3-4c1b-980c-b728ba13abf4)

**Comment by islam2hamy** [comment] 2024-09-03 14:25
It works after activate notifications , but why only with notifications ?

**Comment by wolfsolver** [comment] 2024-09-03 15:24
AutoPost is part of notifiction process (so every day at 8:00 new transaction will be posted).

For better experience is better to disable autopost flag is notification is not set, as in commit https://github.com/wolfsolver/android-money-manager-ex/commit/6c88f473b34848fcc6f3b4087d25c8749381fa41
