### ISSUE TITLE
App crash during add or edit entities -> payees

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1735] opened 2024-07-09 06:14 UTC
**Describe the bug**
Creating dublicate payees make app crash
**To Reproduce**
1. Go to payees
2. Click on new with name as ex. (me)
3. Add another payees with the same name (me)
4. App crash , also if try to add new payees with different name , app crash

**Device Information:**
- Device: Redmi note 12
- OS: Android 14
- Storage: Phone storage
- Synchronization: Enabled - never
- Encrypted: no
- App Version: 2024.07.04

**Comment by guanlisheng** [comment] 2024-07-09 16:04
hi @islam2hamy, can you share some detailed logs as we can't reproduce the issue

**Comment by islam2hamy** [comment] 2024-07-09 16:16
Hi @guanlisheng 
here you are
[Subject.txt](https://github.com/user-attachments/files/16146380/Subject.txt)

**Comment by guanlisheng** [comment] 2024-07-10 14:14
nothing special would be found. is it reproducible and since which version?

**Comment by islam2hamy** [comment] 2024-07-10 16:48
Now , it  is not reproducible

**Comment by guanlisheng** [comment] 2024-07-11 14:23
ok, would you close it?

seems it related to #1734

**Closed** 2024-08-09 02:53 UTC
Labels: bug
