### ISSUE TITLE
Crashes in the background at 8am everyday

### ISSUE THREAD

**Issue by shrubit** [moneymanagerex/android-money-manager-ex#1199] opened 2018-02-02 18:21 UTC
Every day at 8am I get a message on screen saying MoneyManager EX has crashed. This occurs after restarts and the app not being opened. The device is a Google Pixel 2 running 8.1. Other than that working really well.

Note:
The app is set to sync with a file in Dropbox every 6 hours. Changing this sync interval doesn't seem to make a difference.

Thanks

**Comment by MisterY** [comment] 2018-02-03 00:47
Thanks for the report. This is caused by the recurring transactions notification and I'm not exactly sure how to set it up correctly for Android 8.

**Comment by shrubit** [comment] 2018-02-03 07:41
Sorry I'm not a developer so can't help from that end. Happy to test and feedback though.

**Comment by MisterY** [comment] 2018-03-04 11:36
This should have been fixed in the latest version.

**Comment by snarchio** [comment] 2018-03-04 12:03
I confirm, it never crashes anymore

**Comment by MisterY** [comment] 2018-03-04 13:05
@snarchio, thanks for the confirmation!

**Closed** 2018-03-04 13:05 UTC
