### ISSUE TITLE
App crashes on startup with Oreo 8.1

### ISSUE THREAD

**Issue by mtbboy41** [moneymanagerex/android-money-manager-ex#1178] opened 2017-12-11 23:32 UTC
Happily using moneymanager ex on Nexus 6P on 8.0 . Upgraded to 8.1 and App wont start at all under 8.1

**Comment by bluehelo** [comment] 2017-12-14 21:20
Same on Pixel 2 XL 8.1.  Beta launches ok.

**Comment by MisterY** [comment] 2017-12-15 14:43
Interesting. Thanks for the report.
Can you please confirm if Beta build 970 fixes the issue with crashes on Oreo? If so, the next stable release would follow fairly quickly.
Thanks our new devs for contributing!

**Comment by bluehelo** [comment] 2017-12-15 15:08
Whats working:
Application opens
Syncs to Dropbox and downloads remote file
After sync pulls in all data correctly
Able to create, edit and delete transactions
Able to enter next occurrence of recurring transactions 

Errors:
After clicking the + to enter a new transaction, or entering a new 'next occurrence' the error below comes up (transactions still seem to successfully post).  Error: MMEX: Bank Transaction Process EXCEPTION--> java.lang.NumberFormatException: s == null

**Comment by MisterY** [comment] 2017-12-15 15:26
The error seems to be related to #1179, @velmuruganc.

**Comment by velmuruganc** [comment] 2017-12-15 16:06
I could able create this issue in my mobile and not in the emulator. Looking into this.

**Comment by velmuruganc** [comment] 2017-12-15 16:13
@bluehelo, I found the place where it is throwing the exception and will fix soon.

**Comment by velmuruganc** [comment] 2017-12-16 01:04
@bluehelo & @MisterY , I fixed the issue and created PR #1183

**Comment by shrubit** [comment] 2017-12-16 09:12
Just tried the new beta on 8.1 and all looks good.Not managed to find any problems.

**Comment by MisterY** [comment] 2017-12-16 21:37
OK, let's see if tonight's Beta is good to go. Then perhaps some time next week I could publish the stable version with all the fixes.

**Comment by MisterY** [comment] 2017-12-16 22:32
Update: the sync seems to work in emulator with Android 8! 
There are still several errors displayed and they are a bit misleading. And so are the notifications (i.e. "downloading file" when it is actually uploading). But this seems to only affect notifications.

**Comment by bluehelo** [comment] 2017-12-17 01:37
@MisterY Confirmed that the null error has stopped after most recent beta update. Everything appears to be operating correctly.  Will continue on beta and update if anything changes.

**Comment by MisterY** [comment] 2017-12-17 01:42
Thanks, @bluehelo. Could you confirm that the upload/download messages in the notifications match the actual direction of the file transfer during database sync?
Also, in the emulator, I was always getting an error message for being unable to send a notification on channel null, or something similar. 
I would leave about a week for any issues to be reported from the Beta testing community and then publish a stable version.

**Comment by MisterY** [comment] 2017-12-17 01:44
Closing this issue. Any issues with eventual error messages on real devices should be handled separately.

**Closed by MisterY** 2017-12-17 01:44 UTC
Labels: bug

**Comment by bluehelo** [comment] 2017-12-17 01:51
@MisterY Force sync'ing both upload and download give the message "Downloading database ....."

**Comment by bluehelo** [comment] 2017-12-17 01:59
@MisterY  Sorry should clarify. Popup overlay message is correct when downloading and uploading. In the notification area is where it says Downloading regardless of upload or download operation. I only see it for a few seconds so I consider it purely cosmetic for myself. Function is more important which appears to be 100%.

**Comment by snarchio** [comment] 2017-12-17 06:51
It is museo fault fixing the crash. I picked the sale message that is for upload.
It creates a Notification with a "Download" message and the update a it accordi gli ti the direction.
It would be good a neutral message as "Connecting" or something similar but must be translated in all languages

**Comment by MisterY** [comment] 2017-12-17 08:37
That seems like a good suggestion. Perhaps we set the message to something like "synchronising" later.
